language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_56f6ed9ca489_key -iv $encrypted_56f6ed9ca489_iv
  -in service-account.json.enc -out service-account.json -d
- npm config set spin false
install:
- npm install
script:
- npm run build
deploy:
  provider: gae
  key_file: service-account.json
  project: restaskest84
  on:
    all_branches: true
  skip_cleanup: true
