language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_e432962c2b68_key -iv $encrypted_e432962c2b68_iv
  -in service-account.json.enc -out service-account.json -d
- npm i -g npm
install:
- npm install
script:
- npm run build
deploy:
  provider: gae
  key_file: service-account.json.enc
  project: restaskest-api
  on:
    all_branches: true
  skip_cleanup: true
  no_promote: true
