language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
before_install:
    - "npm config set spin false"
install:
    - npm install
script:
    - npm run build
deploy:
    provider: heroku
    api_key:
        secure: a1ec4e34-2166-4061-886a-1b5b455223e8
    app: restaskest-api