language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
 - npm i -g npm
 - openssl aes-256-cbc -K $encrypted_56f6ed9ca489_key -iv $encrypted_56f6ed9ca489_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
install:
- npm install
script:
- npm run build
deploy:
  provider: gae
  key_file: credentials.tar.gz.enc
  project: restaskest84
  on:
    all_branches: true
  skip_cleanup: true
  no_promote: true

